### ISSUE TITLE
support multiple users connecting the same proxy

### ISSUE THREAD

**Issue by fperegrinvs** [lstern/SWProxy-plugins#13]
I guess we should write one file per user ut also have a config option that would write data to a unified csv. Its worth noting that extra columns should be appended to file's end to maintain retro-compatibility

**Comment by daniellhotka** [comment]
I think it might be tricky to implement simultaneous logging from two accounts and two devices because currently it reads the BattleStart event and starts a timer, then once it reads the BattleResult it takes the info provided the first time around and merges the information. I guess if you have 2 sets of events you need to add the wizard_id to the as a persistent config parameter and compare it when BattleResult comes up. I don't know enough about Python to know if it would work with 2 instances of the config 'waiting' to finish.

It's much easier if you consider a person with 2 accounts and one device, all you have to do is tag the user name on the end and it's sorted.
