### ISSUE TITLE
Arena Logger

### ISSUE THREAD

**Issue by KilluaFein** [lstern/SWProxy-plugins#32]
The arena logger plugin doesn't log revenge arena, don't know if is a known issue

**Comment by daniellhotka** [comment]
by doesn't log, do you mean it doesn't log at all or is missing the name?

**Comment by KilluaFein** [comment]
doesn't log at all

**Comment by daniellhotka** [comment]
ok. Did you alter the swproxy.config file with the required true/false flag?
`"log_arena": true,`

**Comment by KilluaFein** [comment]
Yeah i copied the .config file from the zip into the proxy folder. The only false is "log_wipes", I don't know what is that for

**Comment by daniellhotka** [comment]
log_wipes tells the plugins whether to log run losses or not. 

Ok, the problem is what I suspected. The code is being refactored to allow for better different characters (Chinese, Korean, etc) and Google Sheets integration. The python dependencies are not incorporated into the current SWProxy.exe and therefore you have to install python (on windows, it's included on many linux and mac distros), install the correct dependencies and run the proxy manually. I'm not sure when these changes will be rolled out into the main SWProxy release.

**Comment by fperegrinvs** [comment]
I'll create a custom build (for windows) soon

**Comment by KilluaFein** [comment]
thank you guys! amazing work :)

**Comment by KilluaFein** [comment]
well, thats odd.. now is working. maybe a couple hours ago my server lagged during a few revenge, but now is logging fine! sry :D
